### ISSUE TITLE
No module named 'pyfiglet'

### ISSUE THREAD

**Issue by kikieri** [pedrocatalao/rgb-ascii-art#2]
Love this script for my terminal, using m1max osx,
since an python update I got this:
Traceback (most recent call last):
  File "/Users/username/colorize_ascii.py", line 5, in <module>
    import pyfiglet
ModuleNotFoundError: No module named 'pyfiglet' 

But I got the module installed.
Problem:
https://github.com/Homebrew/homebrew-core/issues/76621

How can I fix it and make it work again?

**Comment by pedrocatalao** [comment]
Hi, I totally missed this question. Did you manage to fix it?
It might be that now you are running the rgb script with a different installation of python from the one that has pyfiglet installed.

**Comment by pedrocatalao** [comment]
I suggest you try this:

```
python -m pip install pyfiglet
```

If Python detects the pip module as non-existent, which is useful in many cases (like installations that did not install pip), use the [built-in ensurepip module](https://docs.python.org/3/library/ensurepip.html) to install it:

```
python -m ensurepip
```

If that doesn't work feel free to reopen the issue :)
